name       : libsigrokdecode
version    : 0.5.2
release    : 5
source     :
    - https://sigrok.org/download/source/libsigrokdecode/libsigrokdecode-0.5.2.tar.gz : e08d9e797c54eccf3144da631b6e5f1498ac531e51520428df537a1da82583f0
license    : GPL-3.0-or-later
component  : programming.library
summary    : Provides the basic API for sigrok protocol decoders
description: |
    libsigrokdecode is a shared library written in C which provides the basic API for running sigrok protocol decoders. The protocol decoders themselves are written in Python.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
