name       : libsigrokdecode
version    : 0.5.0
release    : 1
source     :
    - http://sigrok.org/download/source/libsigrokdecode/libsigrokdecode-0.5.0.tar.gz : 4aa8579ecea9b421b8ac048a9b18c27e63206839f269374398d89c14a47bd1c1
license    : GPL-3.0
component  : programming.library
summary    : Provides the basic API for sigrok protocol decoders
description: |
    libsigrokdecode is a shared library written in C which provides the basic API for running sigrok protocol decoders. The protocol decoders themselves are written in Python.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
